# Generated by Django 4.1 on 2024-04-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("www", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="kierunek",
            options={"verbose_name_plural": "Kierunki"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name_plural": "Studenci"},
        ),
        migrations.AlterModelOptions(
            name="wydzial",
            options={"verbose_name": "Wydział", "verbose_name_plural": "Wydziały"},
        ),
    ]
